# Generated by Django 6.0 on 2026-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
