# Generated by Django 6.0 on 2026-01-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_contemporaryphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contemporaryphoto',
            old_name='image',
            new_name='images',
        ),
    ]
