# Generated by Django 6.0 on 2026-01-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_rename_image_contemporaryphoto_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contemporaryphoto',
            old_name='images',
            new_name='image',
        ),
    ]
