# Generated by Django 6.0 on 2026-01-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_rename_images_contemporaryphoto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contemporaryphoto',
            old_name='image',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='contemporaryphoto',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
